### ISSUE TITLE
Support quoted identifiers

### ISSUE THREAD

**Issue by joews** [joews/prequel#62]
e.g. `SELECT "not a js identifier" FROM ${data}`.

This must somehow be disambiguated against a String literal (probably in `resolve`).

**Comment by jwhitfieldseed** [comment]
I guess the same applies to integer literals, e.g. `SELECT 0 FROM ${data}`. `0` could be a literal or a property. Looks like literals do have to use `resolve`, at least some of the time.

**Comment by jwhitfieldseed** [comment]
This could be solved with `field_expression = expression` and adding a new `resolve` method, I guess `resolveLiteral` that falls through to the literal value if a matching identifier could not be resolved. This is strongly related to #52.

**Comment by jwhitfieldseed** [comment]
It turns out that is harder than it sounds. We need to add `aggregated_field` into `expression`, because `aggregated_field` is already part of `field_expression`. That then becomes ambiguous with the LHS `operand` in the binary `operator_expression` production. This will have to wait for a proper solution to #52.
